openapi: 3.0.3
info:
  title: Library API
  version: 1.1.0
  description: STD22022
servers:
  - url: https://library.com

paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - $ref: '#/components/parameters/queryPagination'
        - $ref: '#/components/parameters/pathPagination'

      responses:
        200:
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    put:
      tags:
        - Books
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        200:
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /books/borrowed:
    get:
      tags:
        - Books
      summary: List of books on loan
      responses:
        200:
          description: List of books on loan
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /books/available:
    get:
      tags:
        - Books
      summary: List of available books
      security:
        - OAuth2: [ 'ADMINISTRATOR' ]
      responses:
        200:
          description: List of available books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /authors:
    get:
      summary: Get all authors
      operationId: getAuthors
      tags:
        - Authors
      parameters:
        - $ref: '#/components/parameters/queryPagination'
        - $ref: '#/components/parameters/pathPagination'

      responses:
        200:
          description: The list of filtered authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
    put:
      summary: Create or update authors
      operationId: crupdateAuthors
      tags:
        - Authors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Author'
      responses:
        200:
          description: The list of created or updated authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
  /authors/{aId}:
    delete:
      summary: Delete an author
      operationId: deleteAuthor
      tags:
        - Authors
      parameters:
        - name: aId
          in: path
          description: Author identifier to be deleted
          schema:
            type: string
          required: true
      responses:
        200:
          description: The author deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
  /visitors:
    get:
      tags:
        - Visitors
      summary: Get all visitors
      operationId: getAllVisitors
      responses:
        '200':
          description: List of all visitors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Visitor'

  /visitors/{visitorId}:
    get:
      tags:
        - "Visitors"
      summary: Get a visitor by ID
      operationId: getVisitorById
      parameters:
        - in: path
          name: visitorId
          description: ID of the visitor
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Visitor details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Visitor'
  /visitors/{visitorId}/actions:
    get:
      tags:
        - Visitors
      summary: Visitor activities
      parameters:
        - in: path
          name: visitorId
          description: ID of the visitor
          required: true
          schema:
            type: string
        - in: query
          name: fromDate
          description: Date of début
          schema:
            type: string
            format: date-time
        - in: query
          name: toDate
          description: Date of end
          schema:
            type: string
            format: date-time
      responses:
        200:
          description: Visitor activities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VisitorAction'
  /visitors/{visitorId}/borrow/{bookId}:
    post:
      tags:
        - Visitors
      summary: Visitor borrows a book
      operationId: borrowBook
      parameters:
        - in: path
          name: visitorId
          description: ID of the visitor borrowing the book
          required: true
          schema:
            type: string
        - in: path
          name: bookId
          description: ID of the book to be borrowed
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BorrowRequest'
      responses:
        '200':
          description: Book borrowed successfully

  /visitors/{visitorId}/return/{bookId}:
    post:
      tags:
        - Visitors
      summary: Visitor returns a book
      operationId: returnBook
      parameters:
        - in: path
          name: visitorId
          description: ID of the visitor returning the book
          required: true
          schema:
            type: string
        - in: path
          name: bookId
          description: ID of the book to be returned
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReturnRequest'
      responses:
        '200':
          description: Book returned successfully

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        author:
          $ref: '#/components/schemas/Author'
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date
    Author:
      type: object
      properties:
        id:
          type: string
        authorName:
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
    Visitor:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        reference:
          type: string
    VisitorAction:
      type: object
      properties:
        visitorId:
          type: integer
        bookId:
          type: string
        action:
          type: string
          enum:
            - loan
            - return
        timestamp:
          type: string
          format: date-time
    BorrowRequest:
      type: object
      properties:
        idVisitor:
          type: integer
        idBook:
          type: string
        borrowing date:
          type: string
          format: date
    ReturnRequest:
      type: object
      properties:
        idEmprunt:
          type: integer
        idVisitor:
          type: integer
        return date:
          type: string
          format: date
    Sex:
      type: string
      enum:
        - M
        - F
    Topic:
      type: string
      enum:
        - ROMANCE
        - COMEDY
        - OTHER
    Page:
      type: integer
      description: Start at `1`
    PageSize:
      type: integer
      description: Cannot exceed `500`
    crupdateBooks:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        topic:
          $ref: '#/components/schemas/Topic'
        pageNumbers:
          $ref: '#/components/schemas/PageSize'
        releaseDate:
          type: string
          format: date
    UpdateBookAuthor:
      type: object
      properties:
        bookId:
          type: string
        authorId:
          type: string
  responses:
    Responses200Base:
      description: successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: success
    AuthorResponse200:
      description: author list
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/responses/Responses200Base'
              - properties:
                  body:
                    type: array
                    items:
                      $ref: "#/components/schemas/Author"
    BookResponse200:
      description: book list
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/responses/Responses200Base"
              - properties:
                  body:
                    type: array
                    items:
                      $ref: "#/components/schemas/Book"
  parameters:
    queryPagination:
      name: page
      in: query
      schema:
        type: object
        properties:
          page:
            type: string
    pathPagination:
      name: pageSize
      in: path
      schema:
        type: object
        properties:
          pageSize:
            type: integer







